### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by omniwired** [leapwallet/cosmos-extension#47]
error An unexpected error occurred: "https://npm.pkg.github.com/download/@leapwallet/sentry-config/3.4.0/7eeb700affe2cf363fa4cf767b9b697c58191acb: Request failed \"401 Unauthorized\"".
Same with
 "https://npm.pkg.github.com/download/@leapwallet/leap-ui/0.1.9/fc8e49c2a0ff5c1adc522b68ee890f87c2143e08:

**Comment by quertc** [comment]
try adding "@leapwallet/leap-ui": "0.1.32" to "resolutions" (in package.json).

**Comment by cuongn265** [comment]
same here, nothing work, anyone can help?

**Comment by quertc** [comment]
> same here, nothing work, anyone can help?

unfortunately there are some build issues here, it's easier to just move the code you need from the sdk to yours and build in your environment.

**Comment by cuongn265** [comment]
> > same here, nothing work, anyone can help?
> 
> unfortunately there are some build issues here, it's easier to just move the code you need from the sdk to yours and build in your environment.

thanks, the fact that I cannot identify where is the leap ui come from, so I got trouble building the code too

**Comment by baryon2** [comment]
@omniwired We have fixed this issue. You can pull the latest changes and build the project.
